name = "Enhanced"
author = "Spxctre"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f43dad10cc906ca9226a8c96151a28d97a1056fb2bbea4a5cbc3bd0bae40d144"

[versions]
fabric = "0.14.9"
minecraft = "1.19"
