name = "Enhanced"
author = "Spxctre"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e4b5624e74f07b4d88b0c82fda4306a93a566f1d8aaeb7729e9fd954b984b04"

[versions]
fabric = "0.14.9"
minecraft = "1.19"
