name = "Enhanced"
author = "Spxctre"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8dcc2038054973c42f270cdcb08b65ca7ad69acd3a55842f8ee490d9f4b501eb"

[versions]
fabric = "0.14.9"
minecraft = "1.19"
